kafka:
  brokers: ["redpanda:9092"]
  sasl:
    enabled: true
    impersonateUser: false
redpanda:
  adminApi:
    enabled: true
    urls: ["http://redpanda:9644"]
    authentication:
      impersonateUser: false
authentication:
  useSecureCookies: false
  basic:
    enabled: true
authorization:
  roleBindings:
    - roleName: admin
      users:
        - loginType: basic
          name: "admin"
