sources:
  redpanda:
    type: kafka
    bootstrap_servers: redpanda:9092
    group_id: vector-analytics
    topics:
      - analytics-events
    auto_offset_reset: earliest

sinks:
  clickhouse:
    type: clickhouse
    inputs:
      - redpanda
    endpoint: "${CLICKHOUSE_URL}"
    database: "${CLICKHOUSE_DATABASE}"
    table: analytics.events
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 1000
      max_bytes: 5000000
      timeout_secs: 5